import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _indexFile = 'tool/charset/source/index-gb18030.txt';
const _rangesFile = 'tool/charset/source/index-gb18030-ranges.txt';
const _outputFile = 'lib/src/source/charset/generated/gb18030_data.g.dart';

void main() {
  final index = File(_indexFile).readAsBytesSync();
  final ranges = File(_rangesFile).readAsBytesSync();
  final indexRows = _parseRows(utf8.decode(index));
  final rangeRows = _parseRows(utf8.decode(ranges));

  for (var pointer = 0; pointer < indexRows.length; pointer++) {
    if (indexRows[pointer].$1 != pointer) {
      throw StateError('The GB18030 index must have contiguous pointers.');
    }
  }

  final reverse = <(int, int)>[];
  for (final (pointer, codePoint) in indexRows) {
    reverse.add((codePoint, pointer));
  }
  reverse.sort((left, right) {
    final codePoint = left.$1.compareTo(right.$1);
    return codePoint == 0 ? left.$2.compareTo(right.$2) : codePoint;
  });
  final uniqueReverse = <(int, int)>[];
  for (final row in reverse) {
    if (uniqueReverse.isEmpty || uniqueReverse.last.$1 != row.$1) {
      uniqueReverse.add(row);
    }
  }

  final output = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT EDIT BY HAND.')
    ..writeln('// Generated by tool/charset/generate_tables.dart.')
    ..writeln('//')
    ..writeln('// Source: WHATWG Encoding Standard GB18030 indexes.')
    ..writeln(
      '// Source revision: ff1c9a923b5d24f9761b3a2de2c0f07b395f9f6f36519508944de4f0415be81c',
    )
    ..writeln('// Source date: 2024-09-18')
    ..writeln(
      '// Source license: CC BY 4.0; incorporated data follows BSD-3-Clause.',
    )
    ..writeln('// Generated data license: repository project source terms.')
    ..writeln(
      '// Generation parameters: UTF-8 source, pointer/code-point rows,',
    )
    ..writeln(
      '// first pointer for duplicate code points, sorted reverse pairs.',
    )
    ..writeln()
    ..writeln(
      "const String gb18030SourceIdentifier = 'ff1c9a923b5d24f9761b3a2de2c0f07b395f9f6f36519508944de4f0415be81c';",
    )
    ..writeln("const String gb18030SourceDate = '2024-09-18';")
    ..writeln("const String gb18030IndexSha256 = '${sha256.convert(index)}';")
    ..writeln("const String gb18030RangesSha256 = '${sha256.convert(ranges)}';")
    ..writeln()
    ..writeln('const List<int> gb18030TwoByteCodePoints = <int>[')
    ..write(_formatValues(indexRows.map((row) => row.$2)))
    ..writeln('];')
    ..writeln()
    ..writeln(
      '/// Sorted [code point, pointer] pairs for deterministic encoding.',
    )
    ..writeln('const List<int> gb18030TwoByteReversePairs = <int>[')
    ..write(_formatValues(uniqueReverse.expand((row) => [row.$1, row.$2])))
    ..writeln('];')
    ..writeln()
    ..writeln('const List<int> gb18030RangePointers = <int>[')
    ..write(_formatValues(rangeRows.map((row) => row.$1)))
    ..writeln('];')
    ..writeln()
    ..writeln('const List<int> gb18030RangeCodePoints = <int>[')
    ..write(_formatValues(rangeRows.map((row) => row.$2)))
    ..writeln('];');

  final file = File(_outputFile);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(output.toString());
  final formatted = Process.runSync('dart', [
    'format',
    '--output=write',
    _outputFile,
  ]);
  if (formatted.exitCode != 0) {
    throw ProcessException(
      'dart',
      ['format', '--output=write', _outputFile],
      formatted.stderr.toString(),
      formatted.exitCode,
    );
  }
}

List<(int, int)> _parseRows(String source) {
  final rows = <(int, int)>[];
  final pattern = RegExp(r'^\s*(\d+)\s+0x([0-9A-Fa-f]+)', multiLine: true);
  for (final match in pattern.allMatches(source)) {
    rows.add((
      int.parse(match.group(1)!),
      int.parse(match.group(2)!, radix: 16),
    ));
  }
  if (rows.isEmpty) throw StateError('No mapping rows found.');
  return rows;
}

String _formatValues(Iterable<int> values) {
  final output = StringBuffer();
  var column = 0;
  for (final value in values) {
    if (column == 0) output.write('  ');
    output.write('0x${value.toRadixString(16).padLeft(4, '0')}, ');
    column++;
    if (column == 8) {
      output.writeln();
      column = 0;
    }
  }
  if (column != 0) output.writeln();
  return output.toString();
}
